// Vuejs/src/components/Faq.vue
<template>
  <div class="Faq">
    <div class="container">
      <section class="section">
        <h1 class="title has-text-centered">FAQ</h1>
        <h2 class="subtitle is-4 has-text-centered">Loream ipsum blah blah blah</h2>

        <div class="columns" v-if="faqs && faqs.length">
          <div class="column is-one-third" v-for="faq of faqs">
            <div class="card">
              <div class="card-content">
                <p class="title">{{ faq.title }}</p>
                <p class="answer"> {{ faq.body}}</p>
              </div>
            </div>
          </div>
        </div>


      </section>
    </div>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  name: 'Faq',

  data: () => ({
    faqs: [],
    errors: []
  }),

  created() {
    axios.get('https://jsonplaceholder.typicode.com/posts')
      .then(response => {
        this.faqs = response.data.slice(0,10);
      })
      .catch(e => {
        this.errors.push(e)
      })
  }

}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="sass" scoped>
@import '../mediaQ'

.pd
  padding: 2.5em 0 1.5em 0

.answer
  margin-top: 10px !important

.columns
  flex-wrap: wrap    

</style>

// reactjs/src/components/Faq/Faq.js
import React, { Component } from 'react';
import './Faq.css';
import axios from 'axios';

class Faq extends Component {

  constructor(props) {
    super(props);

    this.state = {
      Faqs: []
    };
  }

  componentDidMount() {
      axios.get('https://jsonplaceholder.typicode.com/posts')
          .then(res => {
              const Faqs = res.data.slice(0,10);
              this.setState({ Faqs });
          })
  }

  render() {
    return (
      <div>
      <div className="container">
        <section className="section">
          <h1 className="title has-text-centered">FAQ</h1>
          <h2 className="subtitle is-4 has-text-centered">Loream ipsum blah blah blah</h2>

          <div className="columns">
            <div className="column is-one-third" >
              <div className="card">
                <div className="card-content">
                  <p className="title">{ Faq.title }</p>
                  <p className="answer"> { Faq.body }</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
      </div>
    );
  }
}

export default Faq;
