// reactjs/src/components/Home/Home.js
import React, { Component } from 'react';
import './Home.css';


class Home extends Component {
  render() {

      let heading = "This is my heading"
      let subheading = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

    return (
      <div>
      <section className="hero">
        <div className="hero-body">
          <div className="container">
            <h1 className="title">{ heading }</h1>
            <div className="is-two-thirds column is-paddingless">
              <h2 className="subtitle is-4">{ subheading }</h2>
            </div>
            <a className="button is-large is-primary" id="learn">Learn More</a>
          </div>
        </div>
      </section>

      <section className="section">
      <div className="container">
        <div className="columns pd is-desktop">
          <div className="column is-1 has-text-centered">
            <i className="fa fa-cog is-primary"></i>
          </div>
          <div className="column is-one-third-desktop">
            <p className="title">
              <strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</strong>
            </p>
          </div>
          <div className="column">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
          </div>
        </div>
      </div>

      <div className="columns pd">
        <div className="column">
          <div className="card">
            <div className="card-content">
              <p className="title">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
              </p>
              <p className="subtitle">- Sidirgot</p>
            </div>
          </div>
        </div>
        <div className="column">
          <div className="card">
            <div className="card-content">
              <p className="title">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
              </p>
              <p className="subtitle">- Sidirgot</p>
            </div>
          </div>
        </div>
        <div className="column">
          <div className="card">
            <div className="card-content">
              <p className="title">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
              </p>
              <p className="subtitle">- Sidirgot</p>
            </div>
          </div>
        </div>
      </div>
    </section>
      </div>
    );
  }
}

export default Home;

// Vuejs/src/components/Home.vue
<template>
  <div class="home">
    <section class="hero">
      <div class="hero-body">
        <div class="container">
          <h1 class="title">{{ Heading }}</h1>
          <div class="is-two-thirds column is-paddingless">
            <h2 class="subtitle is-4">{{ Subheading }}</h2>
          </div>
          <a class="button is-large is-primary" id="learn" href="#">Learn More</a>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="container">
        <div class="columns pd is-desktop">
          <div class="column is-1 has-text-centered">
            <i class="fa fa-cog is-primary"></i>
          </div>
          <div class="column is-one-third-desktop">
            <p class="title">
              <strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</strong>
            </p>
          </div>
          <div class="column">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
          </div>
        </div>
      </div>

      <div class="columns pd">
        <div class="column">
          <div class="card">
            <div class="card-content">
              <p class="title">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
              </p>
              <p class="subtitle">- Sidirgot</p>
            </div>
          </div>
        </div>
        <div class="column">
          <div class="card">
            <div class="card-content">
              <p class="title">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
              </p>
              <p class="subtitle">- Sidirgot</p>
            </div>
          </div>
        </div>
        <div class="column">
          <div class="card">
            <div class="card-content">
              <p class="title">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
              </p>
              <p class="subtitle">- Sidirgot</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script>
export default {
  name: 'home',
  data () {
    return {
      Heading: 'This is my heading',
      Subheading: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
    }
  }

}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="sass" scoped>
@import '../mediaQ'

.hero
  background: url('../assets/codingOp.jpg')
  background-size: cover
  h1,h2
    color: #fff
  h2
    margin: 1.5rem 0 2rem 0 !important
  .title
    +mobile
      font-weight: bold
    +tablet
      font-size: 2.5rem
    +desktop
      font-size: 4rem
      margin-top: 2rem

.fa-cog
  font-size: 40px

#learn
  +desktop
    margin-bottom: 2rem
.pd
  +tablet
    padding: 2em 0




</style>
